language: node_js
node_js:
  - "7"

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  provider: script
  skript: sh ./travis-azure-integration.sh
  skip_cleanup: true
  on:
    all_branches: true
